using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VisitorManagementSystem_Capstone.Models
{
    public class Account
    {
        /// <summary>
        /// Unique identifier for each User Account.
        /// Auto-generated by the database.
        /// </summary>
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int AccountId { get; set; }

        /// <summary>
        /// Unique username for login and identification.
        /// </summary>
        [Required]
        public string? Username { get; set; }

        /// <summary>
        /// User's hashed password.
        /// </summary>
        [Required]
        public string? Password { get; set; }

        /// <summary>
        /// User's email address in a valid format.
        /// </summary>
        [Required]
        [DataType(DataType.EmailAddress)]
        public string? Email { get; set; }

        // Navigation properties
        public virtual ICollection<RoomOwner> RoomOwners { get; set; }

        public virtual ICollection<Staff> Staffs { get; set; }
        public virtual ICollection<Admin> Admins { get; set; }
    }
}