using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VisitorManagementSystem_Capstone.Models
{
    /// <summary>
    /// Represents a log entry for any account-related or system-triggered actions performed by or affecting users in the system.
    /// This model is used to keep track of activities such as approvals, requests, deactivations, and administrative decisions for accountability and auditing purposes.
    /// </summary>
    public class AccountActionLog
    {
        /// <summary>
        /// Unique identifier for each logged action.
        /// Auto-generated by the database.
        /// </summary>
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int LogId { get; set; }

        /// <summary>
        /// Describes the type of action performed in the system. This is a required field.
        /// Example values include: "ClockIn", "ClockOut", "Verified", "Denied", "Requested", "Added", "Updated", "Deleted", "Registered".
        /// </summary>
        [Required]
        public string? ActionType { get; set; }

        /// <summary>
        /// Descriptive message or context that explains what the action was.
        /// Example: "requested Visitor John to Room 402."
        /// </summary>
        [Required]
        public required string ActionText { get; set; }

        /// <summary>
        /// Timestamp indicating when the action was performed.
        /// Automatically initialized to the current time.
        /// </summary>
        [Required]
        public required DateTime ActionDateTime { get; set; } = DateTime.Now;

        /// <summary>
        /// Optional foreign key referencing the user affected by the action.
        /// This is used when an action targets another user (e.g., a visitor request or an account update).
        /// </summary>
        public string? TargetUserId { get; set; }

        /// <summary>
        /// Navigation property to the user affected by the action (if applicable).
        /// </summary>
        [ForeignKey(nameof(TargetUserId))]
        public User? TargetUser { get; set; }

        /// <summary>
        /// Required foreign key referencing the user who performed or triggered the action.
        /// </summary>
        [Required]
        public string? UserId { get; set; }

        /// <summary>
        /// Navigation property to the user who initiated the action.
        /// </summary>
        [ForeignKey(nameof(UserId))]
        public User? User { get; set; }
    }
}
