// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisitorManagementSystem_Capstone.Data;

#nullable disable

namespace VisitorManagementSystem_Capstone.Migrations
{
    [DbContext(typeof(VisitorManagementSystemDatabaseContext))]
    [Migration("20250822075011_test2")]
    partial class test2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AccountId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            Email = "default.owner@gmail.com",
                            Password = "AQAAAAIAAYagAAAAEGworE4xLkk9afv0B3spP11ZoGiFKo6hjHOL2F+dN7Ih8o9ZDf9Hcri84YzErMqK1Q==",
                            Username = "roomowner"
                        },
                        new
                        {
                            AccountId = 2,
                            Email = "default.staff@gmail.com",
                            Password = "AQAAAAIAAYagAAAAECMgnaa0nlsEFNYKyY/0wLFVaxFPjhnW9KGGEw4JHnXnhQ5/qofNYvnXgJfJPcj7AQ==",
                            Username = "staff"
                        },
                        new
                        {
                            AccountId = 3,
                            Email = "act.lusamdelictor@gmail.com",
                            Password = "AQAAAAIAAYagAAAAEDav1nOozAS/YpYepAYxmfg8arUJmWPtdJOskBHiZYFoSyk4G3f+1TU0+oTuyivZIg==",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.AccountActionLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("ActionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LogId");

                    b.HasIndex("TargetUserId");

                    b.HasIndex("UserId");

                    b.ToTable("accountActionLogs");
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.Admin", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateAssigned")
                        .HasColumnType("date");

                    b.HasKey("UserId");

                    b.HasIndex("AccountId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            UserId = "ADM-2025-00001",
                            AccountId = 3,
                            DateAssigned = new DateOnly(2025, 1, 1)
                        });
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.CheckInOut", b =>
                {
                    b.Property<int>("CheckInOutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CheckInOutId"));

                    b.Property<DateTime>("CheckInDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CheckedOutBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CheckInOutId");

                    b.ToTable("CheckInOuts");
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.Facility", b =>
                {
                    b.Property<string>("FacilityId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("ClosingTime")
                        .HasColumnType("time");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FacilityStatus")
                        .HasColumnType("bit");

                    b.Property<string>("FloorLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time");

                    b.HasKey("FacilityId");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            FacilityId = "Gym001",
                            Capacity = 5,
                            ClosingTime = new TimeOnly(20, 0, 0),
                            Description = "A fully equipped fitness center featuring cardio machines, free weights, and strength training areas.",
                            FacilityStatus = true,
                            FloorLevel = "Second Floor",
                            Name = "Gymnastic",
                            OpenTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            FacilityId = "Pool001",
                            Capacity = 5,
                            ClosingTime = new TimeOnly(20, 0, 0),
                            Description = "An indoor heated swimming pool suitable for recreational and lap swimming, with locker and shower facilities.",
                            FacilityStatus = true,
                            FloorLevel = "Second Floor",
                            Name = "Swimming Pool",
                            OpenTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            FacilityId = "Study001",
                            Capacity = 5,
                            ClosingTime = new TimeOnly(20, 0, 0),
                            Description = "A quiet, well-lit space with individual desks and power outlets, ideal for reading, studying, and group discussions.",
                            FacilityStatus = true,
                            FloorLevel = "Second Floor",
                            Name = "Study Room",
                            OpenTime = new TimeOnly(10, 0, 0)
                        });
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.FacilityLog", b =>
                {
                    b.Property<int>("FacilityLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityLogId"));

                    b.Property<int>("CheckInOutId")
                        .HasColumnType("int");

                    b.Property<string>("FacilityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("logStatus")
                        .HasColumnType("bit");

                    b.HasKey("FacilityLogId");

                    b.HasIndex("CheckInOutId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("UserId");

                    b.ToTable("FacilityLogs");
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<string>("FloorLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tower")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            FloorLevel = "Second Floor",
                            RoomNumber = "201",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 2,
                            FloorLevel = "Second Floor",
                            RoomNumber = "202",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 3,
                            FloorLevel = "Second Floor",
                            RoomNumber = "203",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 4,
                            FloorLevel = "Second Floor",
                            RoomNumber = "204",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 5,
                            FloorLevel = "Second Floor",
                            RoomNumber = "205",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 6,
                            FloorLevel = "Third Floor",
                            RoomNumber = "301",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 7,
                            FloorLevel = "Third Floor",
                            RoomNumber = "302",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 8,
                            FloorLevel = "Third Floor",
                            RoomNumber = "303",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 9,
                            FloorLevel = "Third Floor",
                            RoomNumber = "304",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 10,
                            FloorLevel = "Third Floor",
                            RoomNumber = "305",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 11,
                            FloorLevel = "Fourth Floor",
                            RoomNumber = "401",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 12,
                            FloorLevel = "Fourth Floor",
                            RoomNumber = "402",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 13,
                            FloorLevel = "Fourth Floor",
                            RoomNumber = "403",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 14,
                            FloorLevel = "Fourth Floor",
                            RoomNumber = "404",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 15,
                            FloorLevel = "Fourth Floor",
                            RoomNumber = "405",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 16,
                            FloorLevel = "Fifth Floor",
                            RoomNumber = "501",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 17,
                            FloorLevel = "Fifth Floor",
                            RoomNumber = "502",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 18,
                            FloorLevel = "Fifth Floor",
                            RoomNumber = "503",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 19,
                            FloorLevel = "Fifth Floor",
                            RoomNumber = "504",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 20,
                            FloorLevel = "Fifth Floor",
                            RoomNumber = "505",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 21,
                            FloorLevel = "Sixth Floor",
                            RoomNumber = "601",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 22,
                            FloorLevel = "Sixth Floor",
                            RoomNumber = "602",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 23,
                            FloorLevel = "Sixth Floor",
                            RoomNumber = "603",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 24,
                            FloorLevel = "Sixth Floor",
                            RoomNumber = "604",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 25,
                            FloorLevel = "Sixth Floor",
                            RoomNumber = "605",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 26,
                            FloorLevel = "Seventh Floor",
                            RoomNumber = "701",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 27,
                            FloorLevel = "Seventh Floor",
                            RoomNumber = "702",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 28,
                            FloorLevel = "Seventh Floor",
                            RoomNumber = "703",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 29,
                            FloorLevel = "Seventh Floor",
                            RoomNumber = "704",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 30,
                            FloorLevel = "Seventh Floor",
                            RoomNumber = "705",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 31,
                            FloorLevel = "Eighth Floor",
                            RoomNumber = "801",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 32,
                            FloorLevel = "Eighth Floor",
                            RoomNumber = "802",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 33,
                            FloorLevel = "Eighth Floor",
                            RoomNumber = "803",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 34,
                            FloorLevel = "Eighth Floor",
                            RoomNumber = "804",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 35,
                            FloorLevel = "Eighth Floor",
                            RoomNumber = "805",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 36,
                            FloorLevel = "Ninth Floor",
                            RoomNumber = "901",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 37,
                            FloorLevel = "Ninth Floor",
                            RoomNumber = "902",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 38,
                            FloorLevel = "Ninth Floor",
                            RoomNumber = "903",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 39,
                            FloorLevel = "Ninth Floor",
                            RoomNumber = "904",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 40,
                            FloorLevel = "Ninth Floor",
                            RoomNumber = "905",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 41,
                            FloorLevel = "Tenth Floor",
                            RoomNumber = "1001",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 42,
                            FloorLevel = "Tenth Floor",
                            RoomNumber = "1002",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 43,
                            FloorLevel = "Tenth Floor",
                            RoomNumber = "1003",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 44,
                            FloorLevel = "Tenth Floor",
                            RoomNumber = "1004",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 45,
                            FloorLevel = "Tenth Floor",
                            RoomNumber = "1005",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 46,
                            FloorLevel = "Eleventh Floor",
                            RoomNumber = "1101",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 47,
                            FloorLevel = "Eleventh Floor",
                            RoomNumber = "1102",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 48,
                            FloorLevel = "Eleventh Floor",
                            RoomNumber = "1103",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 49,
                            FloorLevel = "Eleventh Floor",
                            RoomNumber = "1104",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 50,
                            FloorLevel = "Eleventh Floor",
                            RoomNumber = "1105",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 51,
                            FloorLevel = "Twelfth Floor",
                            RoomNumber = "1201",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 52,
                            FloorLevel = "Twelfth Floor",
                            RoomNumber = "1202",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 53,
                            FloorLevel = "Twelfth Floor",
                            RoomNumber = "1203",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 54,
                            FloorLevel = "Twelfth Floor",
                            RoomNumber = "1204",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 55,
                            FloorLevel = "Twelfth Floor",
                            RoomNumber = "1205",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 56,
                            FloorLevel = "Thirteenth Floor",
                            RoomNumber = "1301",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 57,
                            FloorLevel = "Thirteenth Floor",
                            RoomNumber = "1302",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 58,
                            FloorLevel = "Thirteenth Floor",
                            RoomNumber = "1303",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 59,
                            FloorLevel = "Thirteenth Floor",
                            RoomNumber = "1304",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 60,
                            FloorLevel = "Thirteenth Floor",
                            RoomNumber = "1305",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 61,
                            FloorLevel = "Fourteenth Floor",
                            RoomNumber = "1401",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 62,
                            FloorLevel = "Fourteenth Floor",
                            RoomNumber = "1402",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 63,
                            FloorLevel = "Fourteenth Floor",
                            RoomNumber = "1403",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 64,
                            FloorLevel = "Fourteenth Floor",
                            RoomNumber = "1404",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 65,
                            FloorLevel = "Fourteenth Floor",
                            RoomNumber = "1405",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 66,
                            FloorLevel = "Fifteenth Floor",
                            RoomNumber = "1501",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 67,
                            FloorLevel = "Fifteenth Floor",
                            RoomNumber = "1502",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 68,
                            FloorLevel = "Fifteenth Floor",
                            RoomNumber = "1503",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 69,
                            FloorLevel = "Fifteenth Floor",
                            RoomNumber = "1504",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 70,
                            FloorLevel = "Fifteenth Floor",
                            RoomNumber = "1505",
                            Tower = "Bossa"
                        },
                        new
                        {
                            RoomId = 71,
                            FloorLevel = "Second Floor",
                            RoomNumber = "201",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 72,
                            FloorLevel = "Second Floor",
                            RoomNumber = "202",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 73,
                            FloorLevel = "Second Floor",
                            RoomNumber = "203",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 74,
                            FloorLevel = "Second Floor",
                            RoomNumber = "204",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 75,
                            FloorLevel = "Second Floor",
                            RoomNumber = "205",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 76,
                            FloorLevel = "Third Floor",
                            RoomNumber = "301",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 77,
                            FloorLevel = "Third Floor",
                            RoomNumber = "302",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 78,
                            FloorLevel = "Third Floor",
                            RoomNumber = "303",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 79,
                            FloorLevel = "Third Floor",
                            RoomNumber = "304",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 80,
                            FloorLevel = "Third Floor",
                            RoomNumber = "305",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 81,
                            FloorLevel = "Fourth Floor",
                            RoomNumber = "401",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 82,
                            FloorLevel = "Fourth Floor",
                            RoomNumber = "402",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 83,
                            FloorLevel = "Fourth Floor",
                            RoomNumber = "403",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 84,
                            FloorLevel = "Fourth Floor",
                            RoomNumber = "404",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 85,
                            FloorLevel = "Fourth Floor",
                            RoomNumber = "405",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 86,
                            FloorLevel = "Fifth Floor",
                            RoomNumber = "501",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 87,
                            FloorLevel = "Fifth Floor",
                            RoomNumber = "502",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 88,
                            FloorLevel = "Fifth Floor",
                            RoomNumber = "503",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 89,
                            FloorLevel = "Fifth Floor",
                            RoomNumber = "504",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 90,
                            FloorLevel = "Fifth Floor",
                            RoomNumber = "505",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 91,
                            FloorLevel = "Sixth Floor",
                            RoomNumber = "601",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 92,
                            FloorLevel = "Sixth Floor",
                            RoomNumber = "602",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 93,
                            FloorLevel = "Sixth Floor",
                            RoomNumber = "603",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 94,
                            FloorLevel = "Sixth Floor",
                            RoomNumber = "604",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 95,
                            FloorLevel = "Sixth Floor",
                            RoomNumber = "605",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 96,
                            FloorLevel = "Seventh Floor",
                            RoomNumber = "701",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 97,
                            FloorLevel = "Seventh Floor",
                            RoomNumber = "702",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 98,
                            FloorLevel = "Seventh Floor",
                            RoomNumber = "703",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 99,
                            FloorLevel = "Seventh Floor",
                            RoomNumber = "704",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 100,
                            FloorLevel = "Seventh Floor",
                            RoomNumber = "705",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 101,
                            FloorLevel = "Eighth Floor",
                            RoomNumber = "801",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 102,
                            FloorLevel = "Eighth Floor",
                            RoomNumber = "802",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 103,
                            FloorLevel = "Eighth Floor",
                            RoomNumber = "803",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 104,
                            FloorLevel = "Eighth Floor",
                            RoomNumber = "804",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 105,
                            FloorLevel = "Eighth Floor",
                            RoomNumber = "805",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 106,
                            FloorLevel = "Ninth Floor",
                            RoomNumber = "901",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 107,
                            FloorLevel = "Ninth Floor",
                            RoomNumber = "902",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 108,
                            FloorLevel = "Ninth Floor",
                            RoomNumber = "903",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 109,
                            FloorLevel = "Ninth Floor",
                            RoomNumber = "904",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 110,
                            FloorLevel = "Ninth Floor",
                            RoomNumber = "905",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 111,
                            FloorLevel = "Tenth Floor",
                            RoomNumber = "1001",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 112,
                            FloorLevel = "Tenth Floor",
                            RoomNumber = "1002",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 113,
                            FloorLevel = "Tenth Floor",
                            RoomNumber = "1003",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 114,
                            FloorLevel = "Tenth Floor",
                            RoomNumber = "1004",
                            Tower = "Alto"
                        },
                        new
                        {
                            RoomId = 115,
                            FloorLevel = "Tenth Floor",
                            RoomNumber = "1005",
                            Tower = "Alto"
                        });
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.RoomOccupant", b =>
                {
                    b.Property<int>("OccupantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OccupantId"));

                    b.Property<DateOnly>("DateAssigned")
                        .HasColumnType("date");

                    b.Property<DateOnly>("MoveInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("MoveOutDate")
                        .HasColumnType("date");

                    b.Property<bool>("OccupationStatus")
                        .HasColumnType("bit");

                    b.Property<int>("OwnerType")
                        .HasColumnType("int");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("OccupantId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomOccupants");

                    b.HasData(
                        new
                        {
                            OccupantId = 1,
                            DateAssigned = new DateOnly(2025, 1, 1),
                            MoveInDate = new DateOnly(2025, 1, 1),
                            OccupationStatus = true,
                            OwnerType = 0,
                            OwnerUserId = "OWR-2025-00001",
                            RoomId = 1
                        });
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.RoomOwner", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomOwnerProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("AccountId");

                    b.ToTable("RoomOwners");

                    b.HasData(
                        new
                        {
                            UserId = "OWR-2025-00001",
                            AccountId = 1,
                            RoomOwnerProfilePicture = "/images/default.png"
                        });
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.Staff", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateHired")
                        .HasColumnType("date");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("AccountId");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            UserId = "STF-2025-00001",
                            AccountId = 2,
                            DateHired = new DateOnly(2025, 1, 1),
                            Position = "Receptionist"
                        });
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AccountStatus")
                        .HasColumnType("bit");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("DateCreated")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("ContactNumber")
                        .IsUnique()
                        .HasFilter("[ContactNumber] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "VIS-2025-00001",
                            AccountStatus = true,
                            ContactNumber = "09123456780",
                            DateCreated = new DateOnly(2025, 8, 22),
                            FirstName = "Default",
                            LastName = "Visitor",
                            MiddleName = "-"
                        },
                        new
                        {
                            UserId = "OWR-2025-00001",
                            AccountStatus = true,
                            ContactNumber = "09123456782",
                            DateCreated = new DateOnly(2025, 8, 22),
                            FirstName = "Default",
                            LastName = "Owner",
                            MiddleName = "-"
                        },
                        new
                        {
                            UserId = "STF-2025-00001",
                            AccountStatus = true,
                            ContactNumber = "09123456784",
                            DateCreated = new DateOnly(2025, 8, 22),
                            FirstName = "Default",
                            LastName = "Staff",
                            MiddleName = "-"
                        },
                        new
                        {
                            UserId = "ADM-2025-00001",
                            AccountStatus = true,
                            ContactNumber = "09123456789",
                            DateCreated = new DateOnly(2025, 8, 22),
                            FirstName = "Main",
                            LastName = "Administrator",
                            MiddleName = "-"
                        });
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.VisitLog", b =>
                {
                    b.Property<int>("VisitLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitLogId"));

                    b.Property<DateOnly?>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<string>("AuthorizedUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CheckInOutId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PurposeOfVisit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<bool?>("VerificationStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("VerifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitorUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("logStatus")
                        .HasColumnType("bit");

                    b.HasKey("VisitLogId");

                    b.HasIndex("AuthorizedUserId");

                    b.HasIndex("CheckInOutId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("RoomId");

                    b.HasIndex("VisitorUserId");

                    b.ToTable("VisitLogs");
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.Visitor", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Visitors");

                    b.HasData(
                        new
                        {
                            UserId = "VIS-2025-00001",
                            ProfilePicture = "/images/default.png"
                        });
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.ViewModels.ErrorViewModel", b =>
                {
                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestId")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ErrorViewModels");
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.AccountActionLog", b =>
                {
                    b.HasOne("VisitorManagementSystem_Capstone.Models.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VisitorManagementSystem_Capstone.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TargetUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.Admin", b =>
                {
                    b.HasOne("VisitorManagementSystem_Capstone.Models.Account", "Account")
                        .WithMany("Admins")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VisitorManagementSystem_Capstone.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.FacilityLog", b =>
                {
                    b.HasOne("VisitorManagementSystem_Capstone.Models.CheckInOut", "CheckInOut")
                        .WithMany()
                        .HasForeignKey("CheckInOutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VisitorManagementSystem_Capstone.Models.Facility", "Facility")
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VisitorManagementSystem_Capstone.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CheckInOut");

                    b.Navigation("Facility");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.RoomOccupant", b =>
                {
                    b.HasOne("VisitorManagementSystem_Capstone.Models.RoomOwner", "RoomOwner")
                        .WithMany("OccupiedRooms")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VisitorManagementSystem_Capstone.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("RoomOwner");
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.RoomOwner", b =>
                {
                    b.HasOne("VisitorManagementSystem_Capstone.Models.Account", "Account")
                        .WithMany("RoomOwners")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VisitorManagementSystem_Capstone.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.Staff", b =>
                {
                    b.HasOne("VisitorManagementSystem_Capstone.Models.Account", "Account")
                        .WithMany("Staffs")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VisitorManagementSystem_Capstone.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.VisitLog", b =>
                {
                    b.HasOne("VisitorManagementSystem_Capstone.Models.User", "AuthorizedUser")
                        .WithMany()
                        .HasForeignKey("AuthorizedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VisitorManagementSystem_Capstone.Models.CheckInOut", "CheckInOut")
                        .WithMany()
                        .HasForeignKey("CheckInOutId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VisitorManagementSystem_Capstone.Models.RoomOwner", "RoomOwner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VisitorManagementSystem_Capstone.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VisitorManagementSystem_Capstone.Models.Visitor", "Visitor")
                        .WithMany("VisitLogs")
                        .HasForeignKey("VisitorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthorizedUser");

                    b.Navigation("CheckInOut");

                    b.Navigation("Room");

                    b.Navigation("RoomOwner");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.Visitor", b =>
                {
                    b.HasOne("VisitorManagementSystem_Capstone.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.Account", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("RoomOwners");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.RoomOwner", b =>
                {
                    b.Navigation("OccupiedRooms");
                });

            modelBuilder.Entity("VisitorManagementSystem_Capstone.Models.Visitor", b =>
                {
                    b.Navigation("VisitLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
